### ISSUE TITLE
Implement class to communicate with Google Directions API

### ISSUE THREAD

**Issue by cdaloisio** [CodeforAustralia/rerouteit#3]
A set of methods are required to communicate with the [Google Directions API](https://developers.google.com/maps/documentation/directions/]).

A library already exists:
https://github.com/joshcrews/google-directions-ruby

Keeping in mind that it will also need to support the API optional parameters.

Feel free to fork this or start from the beginning.

**Comment by ghost** [comment]
@cdaloisio 
Did some testing on the gem and found that it can be used for our requirement.

you can specify optional parameters -
eg 
GoogleDirections.new('melbourne', 'perth', :mode => 'walking').xml

**Comment by ghost** [comment]
Pull request #14 
could we close this ?

**Comment by cdaloisio** [comment]
I'll close this as you have done testing on the gem to confirm it's functionality.
