### ISSUE TITLE
Map class returns list of routes

### ISSUE THREAD

**Issue by cdaloisio** [CodeforAustralia/rerouteit#4]
The Map class should return an array of routes based on:
- origin
- destination
- mode of transport

**Comment by ghost** [comment]
There are 4 modes of transport defined 
driving (default) 
walking 
bicycling 
transit 

do you want the method to return data for all the methods or just one of the specified methods at a time ?

**Comment by cdaloisio** [comment]
I think that the original request should return all types and then have them accessible with individual methods. This is because we will need to use each of them to show the various options along side each other.

**Comment by ghost** [comment]
ok. do we need to implement this method server-side ?
our servers will be working extra-time.

can this be implemented client side ?

**Comment by cdaloisio** [comment]
Not a problems if the servers have a little more work. This will probably be better in the end because we can then store any or all of the information from each request if we want to in the future.

**Comment by ghost** [comment]
pull request #14 
can we close this issue ?
